del config.h
del freeglut.cbp
del cmake_install.cmake
del Makefile
del CMakeCache.txt
del freeglut.pc
del CMakeFiles\cmake.check_cache
del CMakeFiles\Makefile.cmake
del CMakeFiles\Makefile2
del CMakeFiles\progress.marks
del CMakeFiles\CMakeDirectoryInformation.cmake
del CMakeFiles\TargetDirectories.txt
del CMakeFiles\CMakeOutput.log
del CMakeFiles\CMakeError.log
